feat: add default value

diff --git a/.github/workflows/cd-ubuntu-ssh.yml b/.github/workflows/cd-ubuntu-ssh.yml
--- a/.github/workflows/cd-ubuntu-ssh.yml
+++ b/.github/workflows/cd-ubuntu-ssh.yml
@@ -23,11 +23,13 @@ jobs:
     name: Deploy to Ubuntu Server
     if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
     runs-on: ubuntu-latest
+    environment:
+      name: production
 
     env:
       SSH_HOST: ${{ secrets.SSH_HOST}}
-      SSH_USER: ${{ secrets.SSH_USER}}
-      SSH_PORT: ${{ secrets.SSH_PORT || '1402'}}
+      SSH_USER: ${{ secrets.SSH_USER || 'khoi'}}
+      SSH_PORT: ${{ '1402'}}
       SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY || secrets.SSH_KEY }}
       SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
       DEPLOY_PATH: ${{ secrets.SSH_TARGET_DIR || '/home/khoi/QuintetX/' }}
@@ -45,6 +47,7 @@ jobs:
           test -n "${SSH_HOST}" || (echo "Missing secret SSH_HOST" && exit 1)
           test -n "${SSH_USER}" || (echo "Missing secret SSH_USER" && exit 1)
           test -n "${SSH_KEY}" || (echo "Missing secret SSH_PRIVATE_KEY or SSH_KEY" && exit 1)
+          test -n "${SSH_PORT}" && test "${SSH_PORT}" != "1402" || (echo "Missing secret SSH_PORT or invalid value" && exit 1)
 
       - name: Configure SSH key and host
         run: |
@@ -96,7 +99,7 @@ jobs:
             --exclude '.ruff_cache/' \
             --exclude '.idea/' \
             ./ "${SSH_USER}@${SSH_HOST}:${DEPLOY_PATH}/"
-
+            echo "Run on server: ssh -p ${SSH_PORT} ${SSH_USER}@${SSH_HOST} 'ls -la ${DEPLOY_PATH}'"
       - name: Install dependencies and run app in tmux
         run: |
           set -euo pipefail
